version: '3.6'
services:
  cen:
    image: ms-bff-json-statistics:1.0.0
    build: .
    ports:
      - "5000:5000"
    volumes:
     - ./app/app.py:/app/app.py
    environment:
      #HOST: eo_db
      #DATABASE: EstadosOpertivosRDSDev
      #USERNAME: eouser
      #PASSWORD: 123456
      TIMEOUT: 10
      LOG_LEVEL: INFO
      TIMEZONE: America/Santiago
  #eo_db:
    #image: postgres
    #environment:
    #  - POSTGRES_PASSWORD=123456
    #  - POSTGRES_USER=eouser
    #  - POSTGRES_DB=EstadosOpertivosRDSDev
    #ports:
    #  - 5432:5432
    #volumes:
    #  - eo_postgreql:/var/lib/postgresql/data
#volumes:
#  eo_postgreql:
