version: '3.6'
services:
  migtra:
    image: ms-bff-work-statistics:1.0.0
    build: .
    ports:
      - "5000:5000"
    volumes:
     - ./app/app.py:/app/app.py
    environment:
      TIMEOUT: 10
      LOG_LEVEL: INFO
      TIMEZONE: America/Santiago
